-- Archivo historico obsoleto.
--
-- No ejecutar este script: pertenece a una primera version del modelo y usa
-- columnas que ya no coinciden con la aplicacion actual (username, rol_id,
-- apellidos, presente, registrado_por).
--
-- Para crear la base desde cero usa:
--   01_schema.sql
--   02_seed.sql
